-- CreateTable
CREATE TABLE "Globalsetting" (
    "settingName" TEXT NOT NULL,
    "AD_HOST" TEXT NOT NULL,
    "AD_PORT" TEXT NOT NULL,
    "AD_DOMAIN" TEXT NOT NULL,
    "AD_BASE_DN" TEXT NOT NULL,
    "SOAP_CUSTOMER_URL" TEXT NOT NULL,
    "SOAP_CUSTOMER_SOAPACTION" TEXT NOT NULL,
    "SOAP_CUSTOMER_USERNAME" TEXT NOT NULL,
    "SOAP_CUSTOMER_PASSWORD" TEXT NOT NULL,
    "inUse" BOOLEAN NOT NULL DEFAULT true,
    "createdById" TEXT NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Globalsetting_pkey" PRIMARY KEY ("settingName")
);

-- AddForeignKey
ALTER TABLE "User" ADD CONSTRAINT "User_warehouseId_fkey" FOREIGN KEY ("warehouseId") REFERENCES "Warehouse"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Globalsetting" ADD CONSTRAINT "Globalsetting_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES "User"("username") ON DELETE RESTRICT ON UPDATE CASCADE;
